rlancaste/stellarsolver

- installLinux.sh
Just a simple change to allow Fedora to work as well.
> Add config to work with Fedora Linux too.

- CMakeLists.txt
> no-implicit-function flag does not exist in Windows

- stellarsolver/externalsextractorsolver.h
- stellarsolver/internalsextractorsolver.h
- stellarsolver/onlinesolver.h
- stellarsolver/parameters.h
- stellarsolver/sextractorsolver.h
- stellarsolver/stellarsolver.cpp
- stellarsolver/stellarsolver.h
- stellarsolver/structuredefinitions.h
> Use #pragma once and fix includes

- stellarsolver/sextractorsolver.cpp
- stellarsolver/stellarsolver.cpp
- stellarsolver/stellarsolver.h
> Remove QThread from StellarSolver base class

- stellarsolver/stellarsolver.cpp
- stellarsolver/stellarsolver.h
> Consolidate functions

- stellarsolver/internalsextractorsolver.cpp
- stellarsolver/stellarsolver.cpp
- stellarsolver/stellarsolver.h
- tester/mainwindow.cpp
> use Q_PROPERTY and remove sync functions

- stellarsolver/stellarsolver.cpp
Register metatypes so that they can be set.
> Register metatypes

- stellarsolver/internalsextractorsolver.cpp
- stellarsolver/internalsextractorsolver.h
> Use ideal thread count to limit maximum number of spwaned threads

- stellarsolver/astrometry/include/astrometry/keywords.h
> Disable Unused to make it compile on Windows

- stellarsolver/externalsextractorsolver.cpp
- stellarsolver/internalsextractorsolver.cpp
- stellarsolver/onlinesolver.cpp
- stellarsolver/sextractorsolver.cpp
- stellarsolver/sextractorsolver.h
- stellarsolver/stellarsolver.cpp
- stellarsolver/stellarsolver.h
This fixes a couple of memory leaks and refactor member variables.
> Fix memory leaks

- stellarsolver/internalsextractorsolver.cpp
> Limit threading to 4 threads or more (multiples of 4).

- stellarsolver/astrometry/include/astrometry/keywords.h
- stellarsolver/externalsextractorsolver.cpp
- stellarsolver/internalsextractorsolver.cpp
So this would work with any even threads 2, 4, 6, ..etc.
> Better solution when we have 2 or more threads

- stellarsolver/internalsextractorsolver.cpp
- stellarsolver/onlinesolver.cpp
- stellarsolver/stellarsolver.cpp
- stellarsolver/structuredefinitions.h
> Use channels from statistics

- CMakeLists.txt
Previous build didn't work on Windows.. this one now builds fine.
> Fix build on Windows by using the same library name but as static

- stellarsolver/internalsextractorsolver.cpp
- stellarsolver/internalsextractorsolver.h
- stellarsolver/parameters.h
also adds partition parameter.
> fix partition initial keep

- debian/control
> Add version to control file to fix dependency

- tester/mainwindow.cpp
- tester/mainwindow.h
Rob, I'm suggesting these keyboard shortcuts for the Tester program for:
zoom in, zoom out, autoscale, pan left/right/up/down, open file, quit
Let me know what you think!
> Add some GUI keyboard shortcuts to the Tester program.

- stellarsolver/externalsextractorsolver.cpp
- tester/mainwindow.cpp
toLatin1() doesn't work well with non ASCII characters like áä
I fixed same issue in KStars
> Replace toLatin1() with toLocal8Bit

- debian/changelog
Updated version in debian control file
> Debian packaging files updated

- stellarsolver/internalsextractorsolver.cpp
- stellarsolver/parameters.cpp
- stellarsolver/parameters.h
- tester/mainwindow.cpp
- tester/mainwindow.ui
Add 2 extraction parameters so that the threshold arg to sep_extract is equal to threshold_bg_multiple * backgroundRMS + threshold_offset. Previously it was hardwired to 2.0
> Add detection thresholds

- stellarsolver/astrometry/blind/tweak2.c
- stellarsolver/stellarsolver.cpp
This seems to fix my KStars testfitsdata.cpp:testParallelSolvers test.
> Make sure stellarsolver does not run after its deleted

- stellarsolver/externalextractorsolver.cpp
This fixes the issue reported on INDI forum: https://www.indilib.org/forum/ekos/13546-alignment-wrong-orientation-shown-on-kstars.html
> Fix astap orientation

- CMakeLists.txt
- cli/README.md
- cli/main.cpp
This a a preview of a command line interface.
It is designed to be mostly drop-in compatible with stellar-solve (only the solving part, no annotation is planned).
Tests and reviews are welcome.
See Instructions in README
@rlancaste 
Is there a way to detect if a CPU-Timeout has happened or no index-files were found?
> [WIP] Add command line interface

- ssolverutils/fileio.cpp
I simplified the code a little bit and improved the error messages, especially when the file does not exist
> Improve image loading

- stellarsolver/astrometry/include/astrometry/ioutils.h
- stellarsolver/astrometry/include/astrometry/os-features-config.h
- stellarsolver/astrometry/include/astrometry/permutedsort.h
- stellarsolver/astrometry/os-features.h
- stellarsolver/astrometry/util/bl-sort.c
- stellarsolver/astrometry/util/fitstable.c
- stellarsolver/astrometry/util/ioutils.c
- stellarsolver/astrometry/util/os-features-test.c
- stellarsolver/astrometry/util/os-features.c
- stellarsolver/astrometry/util/permutedsort.c
- stellarsolver/astrometry/util/qsort_reentrant.c
This fixes Issue #108 and #125 .
The qsort_r fix is backported from astrometry
> Fix qsort warning

- CMakeLists.txt
- cli/README.md
- cli/main.cpp
This PR features some improvements for the recently addded CLI. I would say it is mostly feature-complete now.
- allow system wide installation
- Improve documentation
- Allow parsing of astrometry.cfg file
- Allow specifying a profile
- Fix parameter handling
- Formatting
> CLI Improvements

- stellarsolver/astrometry/include/astrometry/ioutils.h
- stellarsolver/astrometry/qfits-an/anqfits.c
- stellarsolver/astrometry/qfits-an/qfits_memory.c
- stellarsolver/astrometry/qfits-an/qfits_tools.c
- stellarsolver/astrometry/util/fitsbin.c
- stellarsolver/astrometry/util/tic.c
Tried to compile this under MXE https://mxe.cc/ and there was some compile error regarding mmap
> Fix compiler error under MXE
