sexysolver/internalsextractorsolver.cpp, sexysolver/parameters.h
Rob, Here is a speedup I added to KStars.
FWIW, it shouldn't have any effect on your code unless you set params.initialKeep.
Feel free to rename.
The idea is that after sep_extract, it sorts the detections by the oval size, and only performs the "expensive processing", e.g. sep_flux_radius, on the top params.initialKeep detections when sorted by that oval size.
I defaulted it to a large number, so it doesn't have impact, but for my work will set it to, eg. a few hundred or less. So I get that many detections, then get their real HFRs etc, and return the desired number of those.
=> Optionally reduce the number of detections that are processed before filtering

spec/stellarsolver.spec
This is the spec file that allows RPM builds for Fedora and RedHat. Once this is merged, I would request that a webhook is set up in the rlancaste/stellarsolver repo settings.  They type of the webhook is JSON, and the target is:  
https://copr.fedorainfracloud.org/webhooks/github/35866/0ddde295-6a3b-4a2a-b32b-dcb8a0f72858/ 
These are set up in the `settings` section of github, and will allow any changes pushed to trigger a new build of RPM packages for stellarsolver in Copr. These packages are then made available to users directly, as well as pulled in for other builds that require stellarsolver.
Here are the packages created by pointing the build at my branch: https://copr.fedorainfracloud.org/coprs/xsnrg/stellarsolver-bleeding/build/1701395/
Please let me know if you have any …
=> spec: create a spec file for building stellarsolver RPMs

spec/stellarsolver.spec
I missed one of the crazy lib names... the one kstars wants, of course. This adds it.
=> a quick fix to a library name provided by stellarsolver

stellarsolver/parameters.h, stellarsolver/stellarsolver.cpp, stellarsolver/stellarsolver.h
Use const reference whenever possible to save on unnecessary copy-by-value. Set initial keep for some profile to be more reasonable value than 1,000,000 which can take a lot of time to process on embedded systems.
=> Use const and return reference whenever possible.

stellarsolver/internalsextractorsolver.cpp, stellarsolver/internalsextractorsolver.h
The returned Background structure (containing sky background values like the brightness and number of stars detected) had a bug in its values, due to the partitioned computation. This is fixed here.
Also, removed the margin (partitions were separated by 15 pixels in an attempt to avoid duplicate star detections).
Instead I used the SEP flag SEP_OBJ_TRUNC which detects when a star overlaps the edge, and those detections are not used.
This reduces the number of stars not detected without causing duplicates.
=> Fix sky background bug, remove partition margin, skip detections overlapping the edge

tester/mainwindow.cpp, tester/mainwindow.h
One more traunch of shortcuts
- Toggle log display (so that you can see more of the image window)
- Toggle full screen
- Help (so that you can know which keyboard shortcuts there are).
Note, I used the Qt standards for most of them (whenever one existed)
which are defined here: 
https://doc.qt.io/archives/qt-4.8/qkeysequence.html#standard-shortcuts
=> Added shortcuts for help, toggle log display, and fullscreen.

README.md
The wcslib-dev package is required for install on linux, and is listed in the linux install script, but is not included in the 'building the program' instructions in the readme file. This fix adds that package to the list for people (like me) who went direct to the build instructions.
=> Add wcslib-dev to Linux install instructions

stellarsolver/astrometry/include/astrometry/qfits_byteswap.h, stellarsolver/astrometry/include/astrometry/qfits_card.h, stellarsolver/astrometry/include/astrometry/qfits_error.h, stellarsolver/astrometry/include/astrometry/qfits_float.h, stellarsolver/astrometry/include/astrometry/qfits_header.h, stellarsolver/astrometry/include/astrometry/qfits_image.h, stellarsolver/astrometry/include/astrometry/qfits_md5.h, stellarsolver/astrometry/include/astrometry/qfits_memory.h, stellarsolver/astrometry/include/astrometry/qfits_rw.h, stellarsolver/astrometry/include/astrometry/qfits_std.h, stellarsolver/astrometry/include/astrometry/qfits_table.h, stellarsolver/astrometry/include/astrometry/qfits_time.h, stellarsolver/astrometry/include/astrometry/qfits_tools.h, stellarsolver/astrometry/qfits-an/md5.c, stellarsolver/astrometry/qfits-an/qfits_byteswap.c, stellarsolver/astrometry/qfits-an/qfits_card.c, stellarsolver/astrometry/qfits-an/qfits_error.c, stellarsolver/astrometry/qfits-an/qfits_float.c, stellarsolver/astrometry/qfits-an/qfits_header.c, stellarsolver/astrometry/qfits-an/qfits_image.c, stellarsolver/astrometry/qfits-an/qfits_memory.c, stellarsolver/astrometry/qfits-an/qfits_rw.c, stellarsolver/astrometry/qfits-an/qfits_table.c, stellarsolver/astrometry/qfits-an/qfits_time.c, stellarsolver/astrometry/qfits-an/qfits_tools.c, stellarsolver/astrometry/util/md5.c
When packaging StellarSolver for Fedora, we recognized that some files include the old FSF address (check https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address). This PR updates to the current address.
=> Update FSF address in source file headers

CMakeLists.txt, debian/changelog, stellarsolver/internalsextractorsolver.cpp, stellarsolver/stellarsolver.cpp
As the description says... traced a crash in KStars due to a bad rect. This needs to be fixed in KStars as well, but at least stellarsolver should also run check to ensure it is OK.
=> Protect against malformed subframes that might lead to crashes

tester/main.cpp
Tester application doesn't work on locales that use comma as decimal
separator
=> Use C locale for numbers

stellarsolver/astrometry/blind/blind.c, stellarsolver/astrometry/blind/blindutils.c, stellarsolver/astrometry/blind/solvedclient.c, stellarsolver/astrometry/blind/solvedfile.c, stellarsolver/astrometry/blind/solver.c, stellarsolver/astrometry/include/astrometry/qfits_header.h, stellarsolver/astrometry/include/astrometry/qfits_image.h, stellarsolver/astrometry/include/astrometry/qfits_table.h, stellarsolver/astrometry/qfits-an/anqfits.c, stellarsolver/astrometry/qfits-an/qfits_card.c, stellarsolver/astrometry/qfits-an/qfits_error.c, stellarsolver/astrometry/qfits-an/qfits_image.c, stellarsolver/astrometry/qfits-an/qfits_memory.c, stellarsolver/astrometry/qfits-an/qfits_rw.c, stellarsolver/astrometry/qfits-an/qfits_table.c, stellarsolver/astrometry/qfits-an/qfits_time.c, stellarsolver/astrometry/qfits-an/qfits_tools.c, stellarsolver/astrometry/util/ioutils.c, stellarsolver/astrometry/util/log.c, stellarsolver/astrometry/util/os-features.c, stellarsolver/astrometry/util/permutedsort.c, stellarsolver/astrometry/util/tic.c
Looks like with Craft on Windows now it's no longer possible to include unistd.h, which didn't exist on Windows but believe there was a dummy file there so that it compiles.
=> Make it compile on Craft Windows by not including unistd.h

spec/stellarsolver.spec
This fixes a build problem for Fedora and switches from using the RPM setup macro to the autosetup macro in the spec file.
Branch build here: https://copr.fedorainfracloud.org/coprs/xsnrg/stellarsolver-bleeding/build/3140971/
=> Spec autosetup

stellarsolver/externalextractorsolver.cpp
On some distro (openSUSE, Fedora, etc), ASTAP is packaged so that it's installed on `/usr/bin`. This commit add support for detecting ASTAP in the aforementioned location.
=> Detect ASTAP also in /usr/bin

stellarsolver/internalextractorsolver.cpp
Increases the min margin size so that larger stars near partition boundaries don't get lost.
=> Increase the min margin when partitioning and solving

stellarsolver/internalextractorsolver.cpp, stellarsolver/internalextractorsolver.h
Any function that is executed by QtConcurrent::run cannot be cancelled, so all the cancel code is invalid.
Perhaps we must ensure that imageData passed to extractor MUST remain valid up until the extractor is completed.
=> extractPartition cannot be cancelled

stellarsolver/internalextractorsolver.cpp, stellarsolver/internalextractorsolver.h
Protect the QList futures with a mutex.
That is, whenrunSEPExtractor() is runnng, waitSEP() will block until() runSEPExtractor is done -- so the destructor and the abort() method will block until runSEPExtractor is done.
=> Protect the futures QList with a mutex

stellarsolver/onlinesolver.cpp
It seems I closed yesterday the PR inadvertently. Sorry.Here it goes again.
1. Fix the orientation if using online astrometry.
2. Use HTTPS for astrometry-API-URL. Without secure protocol you do not get the log file.
=> Fix online astrometry orientation & HTTPS header for server

README.md
Small issue I found today while trying to compile it under Linux after cding into build/ the right path would be `../` cause `../stellarsolver/` doesn't contain CMakeList
=> Fix Linux compilation instructions

CMakeLists.txt
The CMakeLists.txt obtains a flag whether Qt5 or Qt6 is used. This makes it possible using it in both a Qt5 and Qt6 environment.
=> Support for both Qt5 and Qt6

stellarsolver/stellarsolver.cpp
The multiscales parallelism didn't take into account downsampling when creating the spawned solvers, so those solvers had the wrong scalelo and scalehi, and then they might reject needed index files. This issue doesn't happen with other forms of parallelism, just with multiscale.
=> bugfix when using multiscales with downsampling

spec/stellarsolver.spec
remove the -v option from %prep as it is no longer supported
=> SpecPrepUpdate: remove the -v option from %prep

cli/main.cpp, ssolverutils/fileio.cpp, ssolverutils/fileio.h
Adds a new feature for the new `cli` program, which I find very handy. Thanks btw. for this `cli`! :slightly_smiling_face:
No checks for existing file are done here, thus the warning is given in the help message. If this behavior is not wanted, I can try and built in a check-and-ask-the-user function.
=> Implement saving fits with solution data via cli
